### ISSUE TITLE
Theme won't install

### ISSUE THREAD

**Issue by RyanSinger** [dwrensha/wordpress-sandstorm#20]
I got the following error: 
<img width="1280" alt="screen shot 2016-02-28 at 2 21 41 pm" src="https://cloud.githubusercontent.com/assets/2665386/13381322/28ce19b2-de27-11e5-96bc-49887245288f.png">

I opened the zip and the style.css is right there. How should I troubleshoot this?

**Comment by RyanSinger** [comment]
I can email a copy of the theme zip to help reproduce, if you'd like.

**Comment by RyanSinger** [comment]
The theme I'm trying to install:
[themeforest-4732415-tfingi-responsive-multipurpose-wordpress-theme.zip](https://github.com/dwrensha/wordpress-sandstorm/files/150193/themeforest-4732415-tfingi-responsive-multipurpose-wordpress-theme.zip)

**Comment by paulproteus** [comment]
Hi @RyanSinger ! Let me take a look at this later today. Thanks for filing the issue!

**Comment by RyanSinger** [comment]
@jgcrossman2 fixed it somehow.

**Comment by RyanSinger** [comment]
I think it was an error with the theme.

**Comment by paulproteus** [comment]
Well that's great to hear! If you're satisfied, you can close the issue.
