### ISSUE TITLE
setup https page with wordpress on sandstorm

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/wordpress-sandstorm#25]
When I setup a wordpress  page on sandstorm and update my name server as advised I can only open the webpage via http and not https. I know there would be the need to store my private certificate within the wordpress instance or somehow use a similar feature as sandcats has to get letsencrypt certs which ends in the same situation where my private cert and key must be stored in the instance.

Any ideas how this can be solved?

**Comment by dwrensha** [comment]
I think we're eventually going to want to support a setup where private keys and certificates are stored in grains, but we're not there yet. Today, getting this to work is going to require configuration outside of Sandstorm.

What error do you get when you try to visit the site on https? Are you using Sandcats?

If you're using nginx or something similar in front of your Sandstorm server, then I think you should be able to configure your certificate there.

**Comment by JamborJan** [comment]
(I guess) the main problem is that I'm running a Sandstorm instance with Sandcats (basic setup) which doesn't allow me a proxy ngingx between the www and the sandstorm server (see http://stackoverflow.com/questions/33268092/nginx-forward-ssl-connection-to-another-server).

I know  that I can run Sandstorm with an own certificate instead of Sandcats and at least a hand full of websites with workarounds but thats not the goal. I want to create new Wordpress instances in my existing setup which are accessible via https. Its not possible today but I want it and I want to help achieving this :-)

So what can I do?

**Comment by xet7** [comment]
This issue was moved to wpsandstorm/wordpress-sandstorm#19
