### ISSUE TITLE
Permalinks change every time the grain is opened

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/wordpress-sandstorm#29]
As the name says, *perma*links shout stay the same, always.

# Current situation
Always after re-opening a grain the permalink will change:

![bildschirmfoto_2016-11-28_um_16_02_08](https://cloud.githubusercontent.com/assets/7508960/20673180/6a85f2aa-b584-11e6-8e84-20209bd00e0e.png)

![bildschirmfoto_2016-11-28_um_16_08_27](https://cloud.githubusercontent.com/assets/7508960/20673542/c12f5ce4-b585-11e6-919e-5adfbc670372.png)

The issue is not as big when you know, that you always can use the main link, displayed on the dashboard.

![bildschirmfoto_2016-11-28_um_16_11_56](https://cloud.githubusercontent.com/assets/7508960/20673457/85da8664-b585-11e6-8137-f024ec15b7cf.png)

# Desired situation
To avoid confusion of the user, the permalink should always be displayed with the never changing url which is displayed on the dashboard page.

**Comment by xet7** [comment]
This issue was moved to wpsandstorm/wordpress-sandstorm#23
