### ISSUE TITLE
WordPress grain cannot beopened anymore

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/wordpress-sandstorm#3]
Since 0.68 of Sandstorm has been installed I cannot open the WordPress App as owner anymore:
![grain_not_found](https://cloud.githubusercontent.com/assets/7508960/6846420/97c2dcdc-d3be-11e4-9976-01c891153240.png)

Making a backup and restoring it also fails:
![error_500](https://cloud.githubusercontent.com/assets/7508960/6846426/9d8427a2-d3be-11e4-9ed0-ea426c78cfee.png)

I can create a new instance of WordPress and it's working. I only created this issues just in case something unforeseen happened during migration which needs to be taken care of.

Edit: now I thought I'm smart and pixleize the URL in bith cases. BUt maybe in the first one it would be of interest that URL says ```8K8ETDhsvzGbMe3Baybgh5``` and the error message is looking for somethig different.

JJ

**Comment by dwrensha** [comment]
Eek. This is troubling. Do you continue to get the "No such grain for public ID ..." error after reloading the page? Is there anything interesting in the grain logs?

**Comment by JamborJan** [comment]
Hey @dwrensha 

Yea the message is always there, when I donload the backup, I cannot restore it, then the message error 500 is shown. The log says:

```
** SANDSTORM SUPERVISOR: Starting up grain.
/ekam-provider/canonical/sandstorm/supervisor.c++:1121: warning: ip_tables kernel module not loaded; cannot set up transparent network forwarding.
started php-fpm. status code: 0
started nginx. status code: 0
2015/03/30 11:55:17 [emerg] 36#0: io_setup() failed (38: Function not implemented)
2015/03/30 11:55:17 [emerg] 37#0: io_setup() failed (38: Function not implemented)
2015/03/30 11:55:17 [emerg] 35#0: io_setup() failed (38: Function not implemented)
2015/03/30 11:55:17 [emerg] 38#0: io_setup() failed (38: Function not implemented)
```
For me it's no big issue, I have created a new grain and rebuild my page. Everything fine here. I only want to point that out just in case there is a hidden bug causing this. If you like I can send you a link to my backup file to check that but I would rather not have this public shared. Let me know if that would help.

**Comment by dwrensha** [comment]
I think I found the source of the backup/restore problem: https://github.com/sandstorm-io/sandstorm/pull/311

**Comment by JamborJan** [comment]
Ok, then I will test that as soon as the build has been done and distributed. Any other thing I can do here?

**Comment by JamborJan** [comment]
I guess this one can be closed. Issue has been resolved. The problem never occurred again for me.
