### ISSUE TITLE
404s are not nice formatted

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/wordpress-sandstorm#31]
Usually templates offer nice formatted 404 error pages including the possebility to incude a search form etc. Unfortunately the sandstorm version doesn't have that. 

I'm not quite at the point where I can nail down the root cause but I will try to find something.

@dwrensha can you maybe please add some intsruction to [README.md](https://github.com/dwrensha/wordpress-sandstorm/blob/master/README.md) so that I can make a build to test my changes?

What you get today when you open a not existing URL like mydomain.com/something/wrong:
![bildschirmfoto 2017-02-26 um 21 33 46](https://cloud.githubusercontent.com/assets/7508960/23343410/4dac48ea-fc6b-11e6-99bd-866a9f078327.png)

What you might want (example):
![bildschirmfoto 2017-02-26 um 21 30 43](https://cloud.githubusercontent.com/assets/7508960/23343401/2e6641e8-fc6b-11e6-8a37-99b377183c3b.png)

**Comment by dwrensha** [comment]
Sandstorm does not currently provide a way for apps to specify custom 404 pages. In case you're curious, the code that servers the 404 right now is: https://github.com/sandstorm-io/sandstorm/blob/v0.204/shell/server/pre-meteor.js#L133-L145. In theory it would be possible to enhance Sandstorm's current hacky web publishing feature to allow custom 404 pages. The longer-term plan is to use the interfaces described in `web-publishing.capnp`. In particular, it describes a notion of "not-found entities": https://github.com/sandstorm-io/sandstorm/blob/v0.204/src/sandstorm/web-publishing.capnp#L77-L79.

**Comment by xet7** [comment]
This issue was moved to wpsandstorm/wordpress-sandstorm#25
