### ISSUE TITLE
Pages which are not referenced in menus are missing (404s)

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/wordpress-sandstorm#32]
When you are creating a page in Wordpress which ist not referenced in an active and visible menu it's not copied to the public static space when rebuilding the page. You'll always get 404s when you try to open that specific page. When you download the backup of a worpress grain the page is also missing in the www directory.

**Comment by xet7** [comment]
This issue was moved to wpsandstorm/wordpress-sandstorm#26
