### ISSUE TITLE
On Oasis, uploading a theme prompts for FTP credentials

### ISSUE THREAD

**Issue by kentonv** [dwrensha/wordpress-sandstorm#5]
This is really weird, but on Oasis (and only Oasis), uploading a theme to Wordpress leads to a screen prompting for FTP credentials, with the following message:

> To perform the requested action, WordPress needs to access your web server. Please enter your FTP credentials to proceed. If you do not remember your credentials, you should contact your web host.

The issue does not appear to happen on standard single-machine Sandstorm.

**Comment by dwrensha** [comment]
Fixed in https://github.com/dwrensha/wordpress-sandstorm/commit/10569aa1c6fb32271d391f09bacd996d3ec901d6. I'll release a new version in the near future.

**Comment by dwrensha** [comment]
For the morbidly curious: https://github.com/WordPress/WordPress/blob/cf7e13813f409280900627868eeff1dafb23dffe/wp-admin/includes/file.php#L936-L968
